name: 'Build ESP Master Sketch'

on:
  pull_request:    
    branches:
      - master
    paths:
      - 'ESPMaster/**'
  schedule:
    - cron: '0 12 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile-esp-sketch:
    name: "Build ESP Master Sketch"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip Arduino Libraries
        run: |
          mkdir ~/Arduino
          mkdir ~/Arduino/libraries
          unzip ./ArduinoLibraries/ESPAsyncTCP-master.zip -d ~/Arduino/libraries/
          unzip ./ArduinoLibraries/ESPAsyncWebServer-master.zip -d ~/Arduino/libraries/

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp8266:esp8266:generic"
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - ./ESPMaster
          libraries: |
            - name: Arduino_JSON
              version: 0.2.0
            - name: ArduinoOTA
              version: 1.0.12
            - name: NTPClient
              version: 3.2.1
            - name: ezTime
              version: 0.8.3
            - name: LinkedList
              version: 1.3.3
          cli-compile-flags: |
            - --warnings
            - "none"
